name: Hola Mod4

on: [push]

jobs:
  gret:
    runs-on: ubuntu-latest

    steps:
      - name: Decir Hola
        run: echo "Hola desde github"
      - name: mostrar fecha
        run: date
      - name: Listar archivos
        run: ls-la